"""email_cross_links_supplier_quote_invoice

Revision ID: c364b5f798d9
Revises: 882d9c6221ef
Create Date: 2026-04-21 13:35:17.784050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c364b5f798d9'
down_revision: Union[str, Sequence[str], None] = '882d9c6221ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('related_supplier_id', sa.String(length=36), nullable=True))
    op.add_column('emails', sa.Column('related_quote_id', sa.String(length=36), nullable=True))
    op.add_column('emails', sa.Column('related_invoice_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_emails_related_invoice_id'), 'emails', ['related_invoice_id'], unique=False)
    op.create_index(op.f('ix_emails_related_quote_id'), 'emails', ['related_quote_id'], unique=False)
    op.create_index(op.f('ix_emails_related_supplier_id'), 'emails', ['related_supplier_id'], unique=False)
    op.create_foreign_key(None, 'emails', 'invoices', ['related_invoice_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'emails', 'suppliers', ['related_supplier_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'emails', 'quotes', ['related_quote_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_index(op.f('ix_emails_related_supplier_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_related_quote_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_related_invoice_id'), table_name='emails')
    op.drop_column('emails', 'related_invoice_id')
    op.drop_column('emails', 'related_quote_id')
    op.drop_column('emails', 'related_supplier_id')
    # ### end Alembic commands ###
