"""tarif_grids table

Revision ID: f4463c135034
Revises: 81e7b3f768d6
Create Date: 2026-04-22 09:17:10.523026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4463c135034'
down_revision: Union[str, Sequence[str], None] = '81e7b3f768d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarif_grids',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_price_ht', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['access_tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_tarif_grids_user_key')
    )
    op.create_index(op.f('ix_tarif_grids_user_id'), 'tarif_grids', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarif_grids_user_id'), table_name='tarif_grids')
    op.drop_table('tarif_grids')
    # ### end Alembic commands ###
